import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';
import { getInfo } from '../calculations/calculations';

const Home: NextPage = () => {
  const [offerInfos, setCount] = useState(getInfo());

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div>
            {offerInfos.map(offerInfo => (
              <div key={offerInfo.role}>
                <div>{offerInfo.role}</div>
                <div>{offerInfo.rate}</div>
                <div>{offerInfo.baseSalary}</div>
                <div>{offerInfo.salaryInclBonus}</div>
                <div>{offerInfo.pension}</div>
              </div>
            ))}
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
